version: "3.9"

services:
  gunicorn_flask_app:
    container_name: rockpaperscisors_flask_app
    image: rockpaperscisorsweb:v1
    build: .
    ports:
      - "5000"
    networks:
      - my-rps-network
    environment:
      - FLASK_APP=api.py
  
  nginx:
    container_name: production_nginx
    image: nginx:latest
    ports:
      - 88:88
    networks:
      - my-rps-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    

networks:
  my-rps-network:

