version: "3.9"

services:
  rps_api_gunicorn_flask:
    container_name: rockpaperscisors_flask_api
    image: rockpaperscisorswebapi:latest
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 5000:5000
    networks:
      - my-rps-network

  
  nginx:
    container_name: production_nginx
    image: nginx:latest
    ports:
      - 88:88
    networks:
      - my-rps-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    

networks:
  my-rps-network:

